<a href="https://colab.research.google.com/github/gowtham777y/KNN-method-for-tissue/blob/main/KNN_Tissue.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("tissue.csv")

In [3]:
df

x1  x2     y
0   7   7   bad
1   7   4   bad
2   3   4  good
3   1   4  good

In [4]:
x=df.drop(columns="y").values #We can also write df.iloc[:,0:2].values
x

array([[7, 7],
       [7, 4],
       [3, 4],
       [1, 4]])

In [6]:
y=df["y"].values.reshape(-1,1)
y

array([['bad'],
       ['bad'],
       ['good'],
       ['good']], dtype=object)

In [7]:
from sklearn.preprocessing import LabelEncoder

In [9]:
le=LabelEncoder()

In [10]:
y=le.fit_transform(y) #Changes y values to 0 and 1

/usr/local/lib/python3.7/dist-packages/sklearn/preprocessing/_label.py:251: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [12]:
y 

array([0, 0, 1, 1])

In [13]:
from sklearn.neighbors import KNeighborsClassifier

In [15]:
classifier=KNeighborsClassifier(n_neighbors=3,metric='euclidean') # 3 nearest neighbors are selected and 
# distance is calculated by euclidean method

In [16]:
classifier.fit(x,y)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='euclidean',
                     metric_params=None, n_jobs=None, n_neighbors=3, p=2,
                     weights='uniform')

In [17]:
classifier.predict([[3,7]])

array([1])